### ISSUE TITLE
Compile errors using go 1.7

### ISSUE THREAD

**Issue by donfranke** [glenn-brown/golang-pkg-pcre#10]
Using go1.7.3 darwin/amd64 on CentOS7 and Mac, I am getting C compile errors when trying to use the pcre package. This did work beautifully before go 1.7.  Perhaps a compiler switch is needed?

hostname:pcrematcher dfranke$ go build main.go
# github.com/glenn-brown/golang-pkg-pcre/src/pkg/pcre
Undefined symbols for architecture x86_64:
  "_pcre_compile", referenced from:
      __cgo_73e035e15f71_Cfunc_pcre_compile in pcre.cgo2.o
     (maybe you meant: __cgo_73e035e15f71_Cfunc_pcre_compile)
  "_pcre_exec", referenced from:
      __cgo_73e035e15f71_Cfunc_pcre_exec in pcre.cgo2.o
     (maybe you meant: __cgo_73e035e15f71_Cfunc_pcre_exec)
  "_pcre_fullinfo", referenced from:
      __cgo_73e035e15f71_Cfunc_pcre_fullinfo in pcre.cgo2.o
     (maybe you meant: __cgo_73e035e15f71_Cfunc_pcre_fullinfo)
  "_pcre_get_stringnumber", referenced from:
      __cgo_73e035e15f71_Cfunc_pcre_get_stringnumber in pcre.cgo2.o
     (maybe you meant: __cgo_73e035e15f71_Cfunc_pcre_get_stringnumber)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by donfranke** [comment]
Problem solved by updating local code to latest version hosted on github

**Comment by kaiqiangzhao** [comment]
I got the same error, how did you solve it ？what is the local code ？@muahtorski
